title = "Leaderboard"  # From Git
gitRepoUrl = "https://github.com/arxkdev/Leaderboard" # From Git

gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"

# From git:
organizationName = "arxkdev"
projectName = "Leaderboard"
url = "https://leaderboard.arxk.cloud"
baseUrl = "/Leaderboard/"
tagline = "Create and manage timed Global Leaderboards with ease."

[home]
enabled = true
includeReadme = true # Optional

[[home.features]]
title = "Simple"
description = "Leaderboard is so simple, you could have an Hourly, Daily, Weekly, Monthly and All Time leaderboard setup in 5 lines of code."

[[home.features]]
title = "Fast"
description = "Leaderboard is fast, it has been optimized to be as fast as it possibly can be without sacrificing features or functionality."

[[home.features]]
title = "Lightweight"
description = "Leaderboard is a lightweight performance friendly library that is designed to be as lightweight as possible."

[[home.features]]

[[classOrder]]
section = "Leaderboard"
classes = ["Leaderboard", "Board", "MemoryShard", "Logger"]

[footer]
style = "dark"
copyright = "Copyright Â© 2024 Arxk. Built with Moonwave and Docusaurus"